name: to_do_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  introduction_screen: ^3.1.14
  lottie: ^3.1.2
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10

flutter_icons:
  image_path: "icons/icon_app.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
